### ISSUE TITLE
'no-self-assign' is not in the README.

### ISSUE THREAD

**Issue by arnochauveau** [buzinas/tslint-eslint-rules#103]

**Comment by buzinas** [comment]
Since ESLint is moving forward pretty fast, it's probably one of the new rules that didn't exist when this project was created. I'll be glad to accept a PR for this, if you want to.

**Comment by jmlopez-rod** [comment]
It seems that the README is missing much more:

- [class-methods-use-this](http://eslint.org/docs/rules/class-methods-use-this)
- [func-call-spacing](http://eslint.org/docs/rules/func-call-spacing)
- [line-comment-position](http://eslint.org/docs/rules/line-comment-position)
- [lines-around-directive](http://eslint.org/docs/rules/lines-around-directive)
- [max-lines](http://eslint.org/docs/rules/max-lines)
- [multiline-ternary](http://eslint.org/docs/rules/multiline-ternary)
- [no-bitwise](http://eslint.org/docs/rules/no-bitwise)
- [no-global-assign](http://eslint.org/docs/rules/no-global-assign)
- [no-mixed-operators](http://eslint.org/docs/rules/no-mixed-operators)
- [no-plusplus](http://eslint.org/docs/rules/no-plusplus)
- [no-prototype-builtins](http://eslint.org/docs/rules/no-prototype-builtins)
- [no-restricted-globals](http://eslint.org/docs/rules/no-restricted-globals)
- [no-restricted-properties](http://eslint.org/docs/rules/no-restricted-properties)
- [no-self-assign](http://eslint.org/docs/rules/no-self-assign)
- [no-tabs](http://eslint.org/docs/rules/no-tabs)
- [no-template-curly-in-string](http://eslint.org/docs/rules/no-template-curly-in-string)
- [no-unsafe-finally](http://eslint.org/docs/rules/no-unsafe-finally)
- [no-unsafe-negation](http://eslint.org/docs/rules/no-unsafe-negation)
- [no-useless-computed-key](http://eslint.org/docs/rules/no-useless-computed-key)
- [no-useless-rename](http://eslint.org/docs/rules/no-useless-rename)
- [object-curly-newline](http://eslint.org/docs/rules/object-curly-newline)
- [object-property-newline](http://eslint.org/docs/rules/object-property-newline)
- [prefer-numeric-literals](http://eslint.org/docs/rules/prefer-numeric-literals)
- [rest-spread-spacing](http://eslint.org/docs/rules/rest-spread-spacing)
- [sort-keys](http://eslint.org/docs/rules/sort-keys)
- [symbol-description](http://eslint.org/docs/rules/symbol-description)
- [unicode-bom](http://eslint.org/docs/rules/unicode-bom)

Since we now have the `rules.ts` file it is easy to compare our list with the one from eslint https://api.github.com/repos/eslint/eslint/contents/lib/rules. I'm making a gulp task to help us keep the rule list in sync with both ESLint and TSLint.
