### ISSUE TITLE
Support no-unused-vars rule like in eslint

### ISSUE THREAD

**Issue by ikokostya** [buzinas/tslint-eslint-rules#171]
Rule [no-unused-vars](https://palantir.github.io/tslint/rules/no-unused-variable/) rule was [deprecated](https://github.com/palantir/tslint/issues/1481) in `tslint`. 

But recommended `TypeScript` options `--noUnusedParameters` and `--noUnusedLocals` have a lot of limitations:
* Cannot be disabled per line or file: https://github.com/Microsoft/TypeScript/issues/12913
* Doesn't support any configuration: https://github.com/Microsoft/TypeScript/issues/12149

Also TypeScript options `noUnusedLocals` and `noUnusedParameters` can produce errors during debugging, when unused temporary variables are not a problem. At this point of view linter is applied after compilation and can be disabled during debugging or testing.

I propose to return this rule back and make it similar to eslint [no-unused-vars](http://eslint.org/docs/rules/no-unused-vars) rule.

**Comment by jmlopez-rod** [comment]
The `--noUnusedParameters` and `--noUnusedLocals` do work better than a linter in my opinion. It is true that you cannot disable the error like the linter but ... (you can, in a different way)

```ts
function someFunctionInProgress(a: number, b: number) {
  console.log("I'm not going to use the value of a, just b:", b);
}
```

This type of function would raise the the error that `a` is being unused. Which is good, now you can remove it before making the function available. In some cases however, you may want to keep the variable in there. To make typescript aware of this simply use the prefix `_`.

```ts
function someFunctionInProgress(_a: number, b: number) {
 console.log("typescript is happy even if i don't use the first argument: b = ", b);
}
```

I much rather add the prefix `_` to the start of the variable and be aware that it is named like that because we do not use the variable than having to add the tslint disable comment.

See <https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#flag-unused-declarations-with---nounusedparameters-and---nounusedlocals> for info on the prefix.

**Comment by ikokostya** [comment]
I known about prefix `_`, but it works only for parameters. Consider situation when tests in project are failed and you need investigate why this happen. Typically during this process you need print some variable or add `debugger` statement, i.e. create temporary variables. In this situation code is syntactically correct, but contains undesirable (for production) constructions. 

For this reason I apply linter only after compilation. Now I must disable `noUnusedParameters` , `noUnusedLocals` rules in `tslint.json` and later should don't forget enable its again every time when I need to add unused variable for debugging. This is very annoying.

Problem can be solved if typescript compiler will add support for error severities: print warnings for unused locals, but compile code anyway.

**Comment by ikokostya** [comment]
`no-unused-vars` was undeprecated in `tslint`. So, this issue can be closed.

**Comment by jmlopez-rod** [comment]
Time to update the docs stating that it is available on tslint. I'll reopen to have it as a reminder.

**Comment by ikokostya** [comment]
Rule `no-unused-var` was deprecated [again](https://github.com/palantir/tslint/pull/3919) in `tslint`. I think this issue should be reopen for further discussion.
