### ISSUE TITLE
Feature request: add computed-property-spacing rule

### ISSUE THREAD

**Issue by ikokostya** [buzinas/tslint-eslint-rules#172]
**Versions**
* tslint-eslint-rules: 3.2.3 
* tslint: 4.3.1

**Problem**

Config:

```js
module.exports = {
    rulesDirectory: 'node_modules/tslint-eslint-rules/dist/rules',
    rules: {
        'array-bracket-spacing': [true, 'never']
   }
};
```

Code
```
Math.floor(arr[ 0]);
```

**Expected behavior**

Get error about extra space:

```js
Math.floor(arr[ 0]);
---------------^
```

**Actual behavior**

No errors.

**Comment by jmlopez-rod** [comment]
Could be related: https://github.com/buzinas/tslint-eslint-rules/issues/162

Currently working on making these test pass: https://github.com/eslint/eslint/blob/master/tests/lib/rules/array-bracket-spacing.js

**Comment by jmlopez-rod** [comment]
Turns out the array-bracket-spacing rule does not handle it, because in your example, that is not an array. For that eslint has the [computed-property-spacing](http://eslint.org/docs/rules/computed-property-spacing) rule which is not yet available in the project. I'll keep this open so that I may start working on the rule.

**Comment by bricka** [comment]
I've just put up a PR to implement this rule: #237

**Comment by trivikr** [comment]
I noticed that PR #237 is merged.
The [README.md](https://github.com/buzinas/tslint-eslint-rules#stylistic-issues) needs to be updated mentioning ter-computed-property-spacing is now available for use. Also, this issue can be closed.

**Comment by ikokostya** [comment]
README.md is updated, thanks. Closing.
