### ISSUE TITLE
Heads-up: t-e-r 4.1.0 broke semver

### ISSUE THREAD

**Issue by Vinnl** [buzinas/tslint-eslint-rules#231]
If you explicitly choose not to do semantic versioning, then there's no problem I guess, but if your goal is to adhere to it, it might be good to know that 4.1.0 broke it. Since it renamed two configuration rules, projects that expected those rules to still be checked in the same way will no longer have that assumption remain valid unless they modify their `tslint.json`, thus making it a breaking change. (i.e. they were unable to upgrade "blindly" to the new minor version.) In other words, it should've been release v5.

It's probably too late now, but this might be good to keep in mind for future releases.

**Comment by jmlopez-rod** [comment]
Yes, this was intentional since v4 was done so that it could support tslint 5. The initial goal was to rename all the rules to have the `ter` prefix since tslint is adding more rules with the name of rules we currently have.

The contributing docs have now been updated to state that all rules in this project need to have the `ter` prefix. Have you found some rule replaced by tslint that breaks the current tslint configuration?

I'll keep this issue open till all the rules are renamed and we release v5.

**Comment by Vinnl** [comment]
> Have you found some rule replaced by tslint that breaks the current tslint configuration?

Not actively, I just read the release notes and renamed my t-e-r rules as specified. It's just that if the behaviour of TSLint's rules was different, then things would've behaved differently if I hadn't done anything, which would mean it was a breaking change.
