### ISSUE TITLE
Please add more maintainers to the repo

### ISSUE THREAD

**Issue by Xapphire13** [buzinas/tslint-eslint-rules#290]
It seems that the currently maintainers don't have enough bandwidth to service this repository, could you add more maintainers to remove burden?

**Comment by buzinas** [comment]
Do you want to be a maintainer, @Xapphire13?

**Comment by Xapphire13** [comment]
I wouldn't mind, but I can't guarantee how available I'd be either haha. But I guess the more the merrier?

**Comment by buzinas** [comment]
I just invited you to be a collaborator.

**Comment by jmlopez-rod** [comment]
@buzinas , will you be providing someone else access to npm so that they can also publish? There is still more work to do to get the project up to date with the latest typescript and tslint rules. I'll try to help out a bit till someone can take care of this. I have just released 5.0 right now which is built with typescript 2.6. About to take it for a ride in another project to see if there are any issues.

**Comment by jmlopez-rod** [comment]
@buzinas I have added [release instructions](https://github.com/buzinas/tslint-eslint-rules/blob/master/CONTRIBUTING.md#releasing-to-npm) for any collaborator that you are willing to give access to npm. If someone could manage this for now to do incremental bug fixes and adding new rules it would be great since I haven't had much time to give to this project. I'll try to help out with code-reviews as much as a can.

**Comment by buzinas** [comment]
I'll be more actively maintaining the repo, and will be adding more maintainers during the process. Thanks for opening this issue!
