### ISSUE TITLE
Do you accept PR to implement enhanced no-throw-literal?

### ISSUE THREAD

**Issue by aleung** [buzinas/tslint-eslint-rules#336]
TSLint core rules includes [no-string-throw](https://palantir.github.io/tslint/rules/no-string-throw/) which equals to ESLint [no-throw-literal](https://eslint.org/docs/rules/no-throw-literal).

However, in _no-throw-literal_ document it says:

> Known Limitations
> Due to the limits of static analysis, this rule cannot guarantee that you will only throw Error objects.

In TSLint, we're able to create a rule using type info to overcome the limitation.

I'd propose a new rule to restricts that only instances of `Error` or its subclass be thrown. Could name the rule `ter-strict-error-throw` or any name suggested.

_TSLint_ team seems to have concern on making the _no_string_throw_ rule type checked and they rejected related PRs before. I'd like to know if _tslint-eslint-rules_ project welcome my proposal before I submit a PR.

**Comment by jmlopez-rod** [comment]
Not familiar with the rule but this project is mainly to act as a mirror to the rules provided by eslint.
Keep in mind that the readme table tries to provide rules from tslint that closely matches the one we want in eslint. If for some reason the tslint rule is not doing what the eslint rules does you are welcome to provide one that matches the behaviour and passes the tests from eslint.

Is there something in

https://github.com/eslint/eslint/blob/master/lib/rules/no-throw-literal.js

that `no-string-throw` doesn't provide?

If so you are welcome to provide `ter-no-throw-literal` provided that you make it pass its tests:

https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-throw-literal.js

Otherwise you might be better off creating your own project where your rules can be hosted.

**Comment by aleung** [comment]
The proposed rule is beyond eslint `no-throw-literal` to address what is described in its "[known limitations](https://eslint.org/docs/rules/no-throw-literal#known-limitations)".

Known your point. Thanks!

**Comment by aleung** [comment]
To who feels this rule useful: I've published it in an individual module [tslint-strict-error-throw](https://www.npmjs.com/package/tslint-strict-error-throw).
