### ISSUE TITLE
README Todos as a Roadmap?

### ISSUE THREAD

**Issue by dotdat** [buzinas/tslint-eslint-rules#79]
Hi, I'm very excited about this repo. However, it seems that there are a lot of non-implemented rules written up in the readme. The contribution guidelines also say something about creating an issue for rules that are not found.

I have two questions about the future of this repo:
1) Could we assume that all items labelled as TODO are effectively items on a roadmap?

2) If there is a rule that we see as TODO should a potential contributor create an issue for this rule first or just create a PR since it's already labelled as a desired feature for this project?

Thanks!

**Comment by buzinas** [comment]
Hi, @dotdat, thanks for your comment!

1) Yes, all the existent ESLint rules that doesn't have a correspondent one in TSLint is on the roadmap (although there is no timeline).

2) It's good to create a issue before the PR, because it avoids different contributors developing the same rule. But, as soon as you open the issue, you can assign it to you, and start contributing :)

Thanks for your time, and I hope to see some rules from you!
